/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 christmas_ball.gltf --transform
Author: Ivanix88 (https://sketchfab.com/Ivanix88)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/christmas-ball-36868988285f4b60b3e389e1aa1bab3f
Title: Christmas Ball
*/

import React, { useRef } from "react"
import { useGLTF } from "@react-three/drei"
import christmas_ball from "../assets/christmas_ball-transformed.glb"
export default function Model(props) {
  const { nodes, materials } = useGLTF(christmas_ball)
  const ref = useRef()
  return (
    <group
      {...props}
      dispose={null}
      rotation={[2 * Math.PI, 0, 6.25]}
      scale={0.63}
    >
      <group ref={ref} rotation={[-Math.PI / 2, 0, 0]} scale={50}>
        <mesh
          geometry={nodes.christmass_ball_inside_0.geometry}
          material={materials.inside}
          scale={0.63}
        />
        <mesh
          geometry={nodes.christmass_ball_ouline_0.geometry}
          scale={0.63}
          material={materials.ouline}
        />
      </group>
      <mesh
        geometry={nodes.glass_glass_0.geometry}
        material={materials.glass}
        position={[0, 55, 0]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={50}
      />
    </group>
  )
}

useGLTF.preload(christmas_ball)
