/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 Earth.gltf --transform
Author: kaede256 (https://sketchfab.com/kaede256)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/planet-earth-bce3ea48781c4f02a8c52d2678220d07
Title: Planet Earth
*/

import React, { useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'
import earth from '../assets/Earth-transformed.glb'
export default function Model(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF(earth)
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]}>
          <group
            name="578a67fb859c4432ad395a9d408af1e7fbx"
            rotation={[Math.PI / 2, 0, 0]}
            scale={0.01}
          >
            <group name="Object_2">
              <group name="RootNode">
                <group
                  name="Earth"
                  rotation={[-Math.PI / 2, 0, 0.68]}
                  scale={358.62}
                >
                  <group
                    name="Earth_Details"
                    position={[0.16, -0.81, 0.59]}
                    rotation={[-0.53, -0.79, -2.96]}
                    scale={0.01}
                  >
                    <mesh
                      name="Earth_Details_Wood_0"
                      geometry={nodes.Earth_Details_Wood_0.geometry}
                      material={materials.Wood}
                    />
                    <mesh
                      name="Earth_Details_Tree_0"
                      geometry={nodes.Earth_Details_Tree_0.geometry}
                      material={materials.Tree}
                    />
                    <mesh
                      name="Earth_Details_Tree_0_1"
                      geometry={nodes.Earth_Details_Tree_0_1.geometry}
                      material={materials.Tree}
                    />
                    <mesh
                      name="Earth_Details_Ice_0"
                      geometry={nodes.Earth_Details_Ice_0.geometry}
                      material={materials.material}
                    />
                    <mesh
                      name="Earth_Details_Blue_0"
                      geometry={nodes.Earth_Details_Blue_0.geometry}
                      material={materials.Blue}
                    />
                    <mesh
                      name="Earth_Details_Sand_0"
                      geometry={nodes.Earth_Details_Sand_0.geometry}
                      material={materials.Sand}
                    />
                    <mesh
                      name="Earth_Details_red_0"
                      geometry={nodes.Earth_Details_red_0.geometry}
                      material={materials.material_7}
                    />
                  </group>
                  <group
                    name="Clouds_and_Stars"
                    position={[-0.58, -0.08, 0.84]}
                    rotation={[-1.55, -0.13, 2.63]}
                    scale={0.04}
                  >
                    <mesh
                      name="Clouds_and_Stars_Ice_0"
                      geometry={nodes.Clouds_and_Stars_Ice_0.geometry}
                      material={materials.material}
                    />
                    <mesh
                      name="Clouds_and_Stars_Star_0"
                      geometry={nodes.Clouds_and_Stars_Star_0.geometry}
                      material={materials.Star}
                    />
                  </group>
                  <mesh
                    name="Earth_Ice_0"
                    geometry={nodes.Earth_Ice_0.geometry}
                    material={materials.material}
                  />
                  <mesh
                    name="Earth_Water_0"
                    geometry={nodes.Earth_Water_0.geometry}
                    material={materials.Water}
                  />
                  <mesh
                    name="Earth_Sand_0"
                    geometry={nodes.Earth_Sand_0.geometry}
                    material={materials.Sand}
                  />
                  <mesh
                    name="Earth_Grass_0"
                    geometry={nodes.Earth_Grass_0.geometry}
                    material={materials.Grass}
                  />
                </group>
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload(earth)
